name: CI GiroDeGado

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  API-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2

      - name: Build API
        run: |
          pwd
          cd '${{ github.workspace }}/bin/api/debug'
          ls
          pwd
          qmake ../../../api/api.pro
          make     

      - name: Build Unit Tests
        run: |
          cd '${{ github.workspace }}/bin/api_tests/debug'
          qmake ../../../api_tests/api_tests.pro
          make

     # - name: Build Gui Tests
     #   run: |
     #     cd '${{ github.workspace }}/bin/gui_tests/debug'
     #     qmake ../../../gui_tests/gui_tests.pro
     #     make  

      - name: Run Unit Tests
        run: |
          cd '${{ github.workspace }}/bin/api_tests/debug'
          chmod +x ./ci_execution.sh
          ./ci_execution.sh "./api_tests/debug/api_tests"

     # - name: Run Gui Tests
     #   run: |
     #     cd '${{ github.workspace }}/bin/gui_tests/debug'
     #     chmod +x ./ci_execution.sh
     #     ./ci_execution.sh "./gui_tests/debug/gui_tests"